apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: swaggy-stacks-production

resources:
- ../../base

patchesStrategicMerge:
- replica-count.yaml
- resource-limits.yaml

images:
- name: swaggy-stacks/backend
  newTag: v1.0.0
- name: swaggy-stacks/frontend
  newTag: v1.0.0

configMapGenerator:
- name: swaggy-stacks-config-prod
  behavior: merge
  literals:
  - ENVIRONMENT=production
  - DEBUG=false
  - ALPACA_PAPER_TRADING=false
  - LOG_LEVEL=INFO

commonLabels:
  environment: production