apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: swaggy-stacks
spec:
  replicas: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: swaggy-stacks
spec:
  replicas: 3