apiVersion: v1
kind: Namespace
metadata:
  name: swaggy-stacks
  labels:
    app.kubernetes.io/name: swaggy-stacks
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: swaggy-stacks-sa
  namespace: swaggy-stacks
  labels:
    app.kubernetes.io/name: swaggy-stacks
    app.kubernetes.io/component: service-account